### ISSUE TITLE
adding paper

### ISSUE THREAD

**Issue by rese1f** [ziqihuangg/Awesome-Evaluation-of-Visual-Generation#1]
Thanks for your awesome list! btw our paper also use reward feedback to improve T2I model, would u consider also include it? : )
[VersaT2I: Improving Text-to-Image Models with Versatile Reward](https://arxiv.org/abs/2403.18493) 27 Mar 2024

**Comment by ziqihuangg** [comment]
Thanks for sharing! I've added VersaT2I to the repository.
